name: template_utils
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  mason: any
  collection: 1.16.0
  path: 1.8.2
  async: 2.10.0

dev_dependencies:
  lints: 2.0.0
  test: 1.21.4

